// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MG_Proto.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MG_5fProto_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MG_5fProto_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MG_5fProto_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MG_5fProto_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MG_5fProto_2eproto;
namespace testprotocol {
class Test;
class TestDefaultTypeInternal;
extern TestDefaultTypeInternal _Test_default_instance_;
}  // namespace testprotocol
PROTOBUF_NAMESPACE_OPEN
template<> ::testprotocol::Test* Arena::CreateMaybeMessage<::testprotocol::Test>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace testprotocol {

// ===================================================================

class Test PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:testprotocol.Test) */ {
 public:
  inline Test() : Test(nullptr) {};
  virtual ~Test();

  Test(const Test& from);
  Test(Test&& from) noexcept
    : Test() {
    *this = ::std::move(from);
  }

  inline Test& operator=(const Test& from) {
    CopyFrom(from);
    return *this;
  }
  inline Test& operator=(Test&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Test& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Test* internal_default_instance() {
    return reinterpret_cast<const Test*>(
               &_Test_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Test& a, Test& b) {
    a.Swap(&b);
  }
  inline void Swap(Test* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Test* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Test* New() const final {
    return CreateMaybeMessage<Test>(nullptr);
  }

  Test* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Test>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Test& from);
  void MergeFrom(const Test& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Test* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "testprotocol.Test";
  }
  protected:
  explicit Test(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MG_5fProto_2eproto);
    return ::descriptor_table_MG_5fProto_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntparamFieldNumber = 2,
    kStrparamFieldNumber = 3,
    kInt64ParamFieldNumber = 4,
    kUintparamFieldNumber = 5,
    kUint64ParamFieldNumber = 6,
    kBytesparamFieldNumber = 7,
  };
  // repeated int32 intparam = 2;
  int intparam_size() const;
  private:
  int _internal_intparam_size() const;
  public:
  void clear_intparam();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_intparam(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_intparam() const;
  void _internal_add_intparam(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_intparam();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 intparam(int index) const;
  void set_intparam(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_intparam(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      intparam() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_intparam();

  // repeated string strparam = 3;
  int strparam_size() const;
  private:
  int _internal_strparam_size() const;
  public:
  void clear_strparam();
  const std::string& strparam(int index) const;
  std::string* mutable_strparam(int index);
  void set_strparam(int index, const std::string& value);
  void set_strparam(int index, std::string&& value);
  void set_strparam(int index, const char* value);
  void set_strparam(int index, const char* value, size_t size);
  std::string* add_strparam();
  void add_strparam(const std::string& value);
  void add_strparam(std::string&& value);
  void add_strparam(const char* value);
  void add_strparam(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& strparam() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_strparam();
  private:
  const std::string& _internal_strparam(int index) const;
  std::string* _internal_add_strparam();
  public:

  // repeated int64 int64param = 4;
  int int64param_size() const;
  private:
  int _internal_int64param_size() const;
  public:
  void clear_int64param();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_int64param(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_int64param() const;
  void _internal_add_int64param(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_int64param();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 int64param(int index) const;
  void set_int64param(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_int64param(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      int64param() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_int64param();

  // repeated uint32 uintparam = 5;
  int uintparam_size() const;
  private:
  int _internal_uintparam_size() const;
  public:
  void clear_uintparam();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_uintparam(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_uintparam() const;
  void _internal_add_uintparam(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_uintparam();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 uintparam(int index) const;
  void set_uintparam(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_uintparam(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      uintparam() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_uintparam();

  // repeated uint64 uint64param = 6;
  int uint64param_size() const;
  private:
  int _internal_uint64param_size() const;
  public:
  void clear_uint64param();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_uint64param(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_uint64param() const;
  void _internal_add_uint64param(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_uint64param();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 uint64param(int index) const;
  void set_uint64param(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_uint64param(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      uint64param() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_uint64param();

  // repeated bytes bytesparam = 7;
  int bytesparam_size() const;
  private:
  int _internal_bytesparam_size() const;
  public:
  void clear_bytesparam();
  const std::string& bytesparam(int index) const;
  std::string* mutable_bytesparam(int index);
  void set_bytesparam(int index, const std::string& value);
  void set_bytesparam(int index, std::string&& value);
  void set_bytesparam(int index, const char* value);
  void set_bytesparam(int index, const void* value, size_t size);
  std::string* add_bytesparam();
  void add_bytesparam(const std::string& value);
  void add_bytesparam(std::string&& value);
  void add_bytesparam(const char* value);
  void add_bytesparam(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& bytesparam() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_bytesparam();
  private:
  const std::string& _internal_bytesparam(int index) const;
  std::string* _internal_add_bytesparam();
  public:

  // @@protoc_insertion_point(class_scope:testprotocol.Test)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > intparam_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> strparam_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > int64param_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > uintparam_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > uint64param_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> bytesparam_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MG_5fProto_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Test

// repeated int32 intparam = 2;
inline int Test::_internal_intparam_size() const {
  return intparam_.size();
}
inline int Test::intparam_size() const {
  return _internal_intparam_size();
}
inline void Test::clear_intparam() {
  intparam_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Test::_internal_intparam(int index) const {
  return intparam_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Test::intparam(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.intparam)
  return _internal_intparam(index);
}
inline void Test::set_intparam(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  intparam_.Set(index, value);
  // @@protoc_insertion_point(field_set:testprotocol.Test.intparam)
}
inline void Test::_internal_add_intparam(::PROTOBUF_NAMESPACE_ID::int32 value) {
  intparam_.Add(value);
}
inline void Test::add_intparam(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_intparam(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.intparam)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Test::_internal_intparam() const {
  return intparam_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Test::intparam() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.intparam)
  return _internal_intparam();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Test::_internal_mutable_intparam() {
  return &intparam_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Test::mutable_intparam() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.intparam)
  return _internal_mutable_intparam();
}

// repeated string strparam = 3;
inline int Test::_internal_strparam_size() const {
  return strparam_.size();
}
inline int Test::strparam_size() const {
  return _internal_strparam_size();
}
inline void Test::clear_strparam() {
  strparam_.Clear();
}
inline std::string* Test::add_strparam() {
  // @@protoc_insertion_point(field_add_mutable:testprotocol.Test.strparam)
  return _internal_add_strparam();
}
inline const std::string& Test::_internal_strparam(int index) const {
  return strparam_.Get(index);
}
inline const std::string& Test::strparam(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.strparam)
  return _internal_strparam(index);
}
inline std::string* Test::mutable_strparam(int index) {
  // @@protoc_insertion_point(field_mutable:testprotocol.Test.strparam)
  return strparam_.Mutable(index);
}
inline void Test::set_strparam(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:testprotocol.Test.strparam)
  strparam_.Mutable(index)->assign(value);
}
inline void Test::set_strparam(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:testprotocol.Test.strparam)
  strparam_.Mutable(index)->assign(std::move(value));
}
inline void Test::set_strparam(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  strparam_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:testprotocol.Test.strparam)
}
inline void Test::set_strparam(int index, const char* value, size_t size) {
  strparam_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:testprotocol.Test.strparam)
}
inline std::string* Test::_internal_add_strparam() {
  return strparam_.Add();
}
inline void Test::add_strparam(const std::string& value) {
  strparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.strparam)
}
inline void Test::add_strparam(std::string&& value) {
  strparam_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:testprotocol.Test.strparam)
}
inline void Test::add_strparam(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  strparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:testprotocol.Test.strparam)
}
inline void Test::add_strparam(const char* value, size_t size) {
  strparam_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:testprotocol.Test.strparam)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Test::strparam() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.strparam)
  return strparam_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Test::mutable_strparam() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.strparam)
  return &strparam_;
}

// repeated int64 int64param = 4;
inline int Test::_internal_int64param_size() const {
  return int64param_.size();
}
inline int Test::int64param_size() const {
  return _internal_int64param_size();
}
inline void Test::clear_int64param() {
  int64param_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Test::_internal_int64param(int index) const {
  return int64param_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Test::int64param(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.int64param)
  return _internal_int64param(index);
}
inline void Test::set_int64param(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  int64param_.Set(index, value);
  // @@protoc_insertion_point(field_set:testprotocol.Test.int64param)
}
inline void Test::_internal_add_int64param(::PROTOBUF_NAMESPACE_ID::int64 value) {
  int64param_.Add(value);
}
inline void Test::add_int64param(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_int64param(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.int64param)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
Test::_internal_int64param() const {
  return int64param_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
Test::int64param() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.int64param)
  return _internal_int64param();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
Test::_internal_mutable_int64param() {
  return &int64param_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
Test::mutable_int64param() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.int64param)
  return _internal_mutable_int64param();
}

// repeated uint32 uintparam = 5;
inline int Test::_internal_uintparam_size() const {
  return uintparam_.size();
}
inline int Test::uintparam_size() const {
  return _internal_uintparam_size();
}
inline void Test::clear_uintparam() {
  uintparam_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Test::_internal_uintparam(int index) const {
  return uintparam_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Test::uintparam(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.uintparam)
  return _internal_uintparam(index);
}
inline void Test::set_uintparam(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  uintparam_.Set(index, value);
  // @@protoc_insertion_point(field_set:testprotocol.Test.uintparam)
}
inline void Test::_internal_add_uintparam(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  uintparam_.Add(value);
}
inline void Test::add_uintparam(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_uintparam(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.uintparam)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
Test::_internal_uintparam() const {
  return uintparam_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
Test::uintparam() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.uintparam)
  return _internal_uintparam();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
Test::_internal_mutable_uintparam() {
  return &uintparam_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
Test::mutable_uintparam() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.uintparam)
  return _internal_mutable_uintparam();
}

// repeated uint64 uint64param = 6;
inline int Test::_internal_uint64param_size() const {
  return uint64param_.size();
}
inline int Test::uint64param_size() const {
  return _internal_uint64param_size();
}
inline void Test::clear_uint64param() {
  uint64param_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Test::_internal_uint64param(int index) const {
  return uint64param_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Test::uint64param(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.uint64param)
  return _internal_uint64param(index);
}
inline void Test::set_uint64param(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  uint64param_.Set(index, value);
  // @@protoc_insertion_point(field_set:testprotocol.Test.uint64param)
}
inline void Test::_internal_add_uint64param(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  uint64param_.Add(value);
}
inline void Test::add_uint64param(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_uint64param(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.uint64param)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
Test::_internal_uint64param() const {
  return uint64param_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
Test::uint64param() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.uint64param)
  return _internal_uint64param();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
Test::_internal_mutable_uint64param() {
  return &uint64param_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
Test::mutable_uint64param() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.uint64param)
  return _internal_mutable_uint64param();
}

// repeated bytes bytesparam = 7;
inline int Test::_internal_bytesparam_size() const {
  return bytesparam_.size();
}
inline int Test::bytesparam_size() const {
  return _internal_bytesparam_size();
}
inline void Test::clear_bytesparam() {
  bytesparam_.Clear();
}
inline std::string* Test::add_bytesparam() {
  // @@protoc_insertion_point(field_add_mutable:testprotocol.Test.bytesparam)
  return _internal_add_bytesparam();
}
inline const std::string& Test::_internal_bytesparam(int index) const {
  return bytesparam_.Get(index);
}
inline const std::string& Test::bytesparam(int index) const {
  // @@protoc_insertion_point(field_get:testprotocol.Test.bytesparam)
  return _internal_bytesparam(index);
}
inline std::string* Test::mutable_bytesparam(int index) {
  // @@protoc_insertion_point(field_mutable:testprotocol.Test.bytesparam)
  return bytesparam_.Mutable(index);
}
inline void Test::set_bytesparam(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:testprotocol.Test.bytesparam)
  bytesparam_.Mutable(index)->assign(value);
}
inline void Test::set_bytesparam(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:testprotocol.Test.bytesparam)
  bytesparam_.Mutable(index)->assign(std::move(value));
}
inline void Test::set_bytesparam(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  bytesparam_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:testprotocol.Test.bytesparam)
}
inline void Test::set_bytesparam(int index, const void* value, size_t size) {
  bytesparam_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:testprotocol.Test.bytesparam)
}
inline std::string* Test::_internal_add_bytesparam() {
  return bytesparam_.Add();
}
inline void Test::add_bytesparam(const std::string& value) {
  bytesparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:testprotocol.Test.bytesparam)
}
inline void Test::add_bytesparam(std::string&& value) {
  bytesparam_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:testprotocol.Test.bytesparam)
}
inline void Test::add_bytesparam(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  bytesparam_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:testprotocol.Test.bytesparam)
}
inline void Test::add_bytesparam(const void* value, size_t size) {
  bytesparam_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:testprotocol.Test.bytesparam)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Test::bytesparam() const {
  // @@protoc_insertion_point(field_list:testprotocol.Test.bytesparam)
  return bytesparam_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Test::mutable_bytesparam() {
  // @@protoc_insertion_point(field_mutable_list:testprotocol.Test.bytesparam)
  return &bytesparam_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace testprotocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MG_5fProto_2eproto
